name: Build Cars Special APK (Release)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-pip python3-setuptools python3-venv \
                              build-essential git zip unzip openjdk-17-jdk
          pip install --upgrade pip
          pip install buildozer cython

      - name: Build Release APK
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: |
          buildozer -v android release

      - name: Upload Release APK
        uses: actions/upload-artifact@v3
        with:
          name: CarsSpecial-release
          path: bin/*.apk
